#!/usr/bin/env python3
"""
HTML to PDF Converter Script
=============================

This script converts HTML files to PDF using Chrome/Chromium headless mode.
It's useful when pandoc's PDF engines (pdflatex, wkhtmltopdf) are not available.

Usage:
    python3 html_to_pdf_converter.py <input.html> [output.pdf]

    # Or make it executable and run directly:
    chmod +x html_to_pdf_converter.py
    ./html_to_pdf_converter.py input.html output.pdf

Examples:
    python3 html_to_pdf_converter.py report.html
    python3 html_to_pdf_converter.py report.html my_report.pdf

Requirements:
    - Google Chrome or Chromium browser installed
    - No additional Python packages needed (uses stdlib only)

Author: Generated by Claude Code
Date: November 23, 2025
"""

import subprocess
import os
import sys


def find_chrome():
    """Find Chrome or Chromium executable on the system."""
    chrome_paths = [
        # macOS
        "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
        "/Applications/Chromium.app/Contents/MacOS/Chromium",
        "/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary",
        "/Applications/Brave Browser.app/Contents/MacOS/Brave Browser",

        # Linux
        "/usr/bin/google-chrome",
        "/usr/bin/chromium",
        "/usr/bin/chromium-browser",
        "/usr/local/bin/chrome",
        "/usr/local/bin/chromium",

        # Windows (if running under WSL)
        "/mnt/c/Program Files/Google/Chrome/Application/chrome.exe",
        "/mnt/c/Program Files (x86)/Google/Chrome/Application/chrome.exe",
    ]

    for chrome_path in chrome_paths:
        if os.path.exists(chrome_path):
            return chrome_path

    return None


def convert_html_to_pdf(html_file, pdf_file=None):
    """
    Convert HTML file to PDF using Chrome headless.

    Args:
        html_file (str): Path to input HTML file
        pdf_file (str, optional): Path to output PDF file.
                                 If not provided, uses same name as HTML with .pdf extension

    Returns:
        bool: True if conversion successful, False otherwise
    """
    # Validate input file
    if not os.path.exists(html_file):
        print(f"Error: HTML file not found: {html_file}")
        return False

    # Determine output file
    if pdf_file is None:
        pdf_file = os.path.splitext(html_file)[0] + '.pdf'

    # Find Chrome
    chrome_path = find_chrome()
    if not chrome_path:
        print("Error: Chrome/Chromium not found on this system.")
        print("\nPlease install one of the following:")
        print("  - Google Chrome: https://www.google.com/chrome/")
        print("  - Chromium: brew install chromium (macOS)")
        print("  - Or use: brew install --cask wkhtmltopdf")
        return False

    print(f"Found Chrome at: {chrome_path}")

    # Convert to absolute path if relative
    html_file = os.path.abspath(html_file)
    pdf_file = os.path.abspath(pdf_file)

    # Build Chrome command
    cmd = [
        chrome_path,
        "--headless",
        "--disable-gpu",
        "--no-sandbox",  # Sometimes needed in certain environments
        "--disable-dev-shm-usage",  # Helps with memory issues
        f"--print-to-pdf={pdf_file}",
        f"file://{html_file}"  # Use file:// protocol for local files
    ]

    try:
        # Run Chrome headless
        result = subprocess.run(
            cmd,
            check=True,
            capture_output=True,
            text=True,
            timeout=60  # 60 second timeout
        )

        # Check if PDF was created
        if os.path.exists(pdf_file):
            file_size = os.path.getsize(pdf_file)
            print(f"✅ Successfully created {pdf_file}")
            print(f"   File size: {file_size:,} bytes ({file_size/1024:.1f} KB)")
            return True
        else:
            print(f"❌ PDF file was not created: {pdf_file}")
            return False

    except subprocess.TimeoutExpired:
        print("❌ Error: Conversion timed out after 60 seconds")
        return False
    except subprocess.CalledProcessError as e:
        print(f"❌ Error running Chrome: {e}")
        if e.stderr:
            print(f"   Error details: {e.stderr}")
        return False
    except Exception as e:
        print(f"❌ Unexpected error: {e}")
        return False


def main():
    """Main entry point for the script."""
    # Check arguments
    if len(sys.argv) < 2:
        print("Usage: python3 html_to_pdf_converter.py <input.html> [output.pdf]")
        print("\nExamples:")
        print("  python3 html_to_pdf_converter.py report.html")
        print("  python3 html_to_pdf_converter.py report.html my_report.pdf")
        sys.exit(1)

    html_file = sys.argv[1]
    pdf_file = sys.argv[2] if len(sys.argv) > 2 else None

    print(f"Converting {html_file} to PDF...")
    success = convert_html_to_pdf(html_file, pdf_file)

    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
